spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/sns"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  session:
    store-type: redis
  data:
    redis:
      host: 127.0.0.1
      port: 6379